- src/main/java/frc/robot/utility/ControllerHelper.java
Creates the controller helper that has the functions: `modify access` and `rumble`. The rumble function has four different versions with varying degrees of simplicity regarding the parameters and default values.
> Controller-Helper

- src/main/java/frc/robot/subsystems/grabber/C2025GrabberIO.java
fixed it's name to be more general and to match with the inputs and function names
> Beam Break name fix

- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/config/C2025RobotFactory.java
- src/main/java/frc/robot/config/RobotFactory.java
- src/main/java/frc/robot/subsystems/led/Led.java
- src/main/java/frc/robot/subsystems/led/LedCandleIo.java
- src/main/java/frc/robot/subsystems/led/LedColor.java
- src/main/java/frc/robot/subsystems/led/LedInputs.java
- src/main/java/frc/robot/subsystems/led/LedIo.java
- vendordeps/Phoenix5-5.35.1.json
Also updated Robot to default the RobotFactory to the C2025RobotFactory.
> Added LED subsystem

- src/main/java/frc/robot/RobotContainer.java
Added Operator Controller bindings to set the robot mode. 
These controls are not the final bindings.
The current bindings are:
Y = Net
A = Processor
X = Remove Algae Upper
B = Remove Algae Lower
POV Up = L4
POV Left = L3
POV Right = L2
POV Down = L1
> Added Robot Mode Binding's

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/SuperStructure.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/ArmInputs.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
- src/main/java/frc/robot/subsystems/grabber/Grabber.java
Added a CommandFactory.java for our Commands.
Also added constants for the eight positions
And a command to go to each of those positions
And also made a map to map those positions to the RobotMode Enum
Fixed some of the Commands in the super Structure so that they currently work
In SuperStructure.java the goToPositions should've been a Commands.parallel since it is running functions that already return commands
> Added Arm Placement Positions, Commands, and a Command Factory

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
> Zeroing the Wrist

- src/main/java/frc/robot/config/C2025RobotFactory.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
Made both of the motors have their own different configs
Added a CANcoder onto the shoulder motor
> Arm Config and Shoulder CANcoder

- src/main/java/frc/robot/subsystems/climber/C2025ClimberIO.java
- src/main/java/frc/robot/subsystems/climber/Climber.java
- src/main/java/frc/robot/subsystems/climber/ClimberIO.java
> Zeroing climber

- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/SuperStructure.java
- src/main/java/frc/robot/config/SimRobotFactory.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/ArmIO.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
- src/main/java/frc/robot/subsystems/arm/SimArmIO.java
- src/main/java/frc/robot/subsystems/elevator/C2025ElevatorIO.java
- src/main/java/frc/robot/subsystems/elevator/Elevator.java
- src/main/java/frc/robot/subsystems/elevator/ElevatorIO.java
- src/main/java/frc/robot/subsystems/elevator/SimElevatorIO.java
Separates out the simulation logic for the Arm and Elevator IOs so that the simulation is not dependent on CTRE libraries.
> Add simulation Arm and Elevator IO implementations

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
- src/main/java/frc/robot/subsystems/grabber/Grabber.java
Added constants for its position (not currently set so all of them are zero)
Also added a command to go to the position and then intake until it gets a game piece
And the binding to run the command; left bumper
Also fixed a simulation bug where since the CANcoder is hooked up to the shoulder motor, the simulation thinks the shoulder motor isn't moving. Fixed it by only connecting the CANcoder to the shoulder motor if it is not a simulation
> Added Intaking

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/RobotMode.java
- src/main/java/frc/robot/SuperStructure.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/elevator/Elevator.java
Added incremental values for the Constants for the positions so that you can tell it is moving between the positions
Added a Command to go to the correct position but using Suppliers so that you can change mode while it is going, and it will change where it is going correctly
Also made it so that the elevator will only move while the shoulder is in a safe position for it to move so that the reef is not hit
> Reworked going to positions and added Reef Collision avoidance

- src/main/java/frc/robot/RobotContainer.java
Bound the start button to zero the wrist, elevator, and climber
> Added a Binding to zero everything

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/RobotMode.java
- src/main/java/frc/robot/SuperStructure.java
Made the Default Command for the SuperStructure.java so that it goes to the position where the elevator and wrist are at 0 and the shoulder is vertical
Also fixed some bugs with conflicting controls 
And also made it so that the SuperStructure commands require the SuperStructure by adding a blank run command
> Added a Default Command to the SuperStructure 

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/climber/Climber.java
Added Climber Bindings
Also Added Deploy and Climb functions to the Climber subsystem
> Added Climber Bindings

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/config/C2025RobotFactory.java
- src/main/java/frc/robot/config/RobotFactory.java
- src/main/java/frc/robot/subsystems/drivetrain/CTREDrivetrainIO.java
- src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
- src/main/java/frc/robot/subsystems/drivetrain/DrivetrainIO.java
- src/main/java/frc/robot/subsystems/vision/Vision.java
Made it so that the Vision tells the drivetrain where it is
> Vision syncing with Drivetrain

- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/ArmIO.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
- src/main/java/frc/robot/subsystems/climber/C2025ClimberIO.java
- src/main/java/frc/robot/subsystems/climber/Climber.java
- src/main/java/frc/robot/subsystems/climber/ClimberIO.java
- src/main/java/frc/robot/subsystems/elevator/C2025ElevatorIO.java
- src/main/java/frc/robot/subsystems/elevator/Elevator.java
- src/main/java/frc/robot/subsystems/elevator/ElevatorIO.java
Adding SysId code to the climber, elevator, shoulder, and wrist
> Adding SysId

- src/main/java/frc/robot/RobotContainer.java
It was because we were sequencing the start of the autos.
First, we reset the odometry then we made it to follow position, to go to place on L4, and finally start the path, but since the follow never ends it never started the auto path.
> Fixed a problem with auto paths not running

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/SuperStructure.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/arm/ArmIO.java
- src/main/java/frc/robot/subsystems/arm/C2025ArmIO.java
> Fix zeroing the wrist by making the zero sequence require the superstructure

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/RobotMode.java
- src/main/java/frc/robot/SuperStructure.java
Made it so that if we have an algae the elevator will not go all the way up. Determined if we have an algae by saying we do if we are in an algae robot mode, and we are detecting a game piece.
> Robot will not Hit the Elevator when it has an Algae

- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/RobotMode.java
Made a put Boolean for each value of RobotMode (Except for Coral Station).
Then updated that in Robots robotPeriodic.
> Better RobotMode Display

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/subsystems/grabber/Grabber.java
Made L4 be 8 volts
Made L2 and L3 by 12 volts
> Increased the Coral Placing Speed

- src/main/java/frc/robot/RobotContainer.java
changed climber buttons, "a" on driver controller is reverse the eject button was moved to driver controller button "b",  "y" on driver controller is the climb button, and left bumper on operator controller initializes the climber
> climber buttons

- src/main/java/frc/robot/subsystems/grabber/C2025GrabberIO.java
- src/main/java/frc/robot/subsystems/grabber/Grabber.java
Decreased the algae hold voltage to -1.5
Added a SupplyCurrentLimit onto the grabber of 15.0
Both of these make it work better and help stop the grabber motor from overheating when holding an algae
> Grabber Algae Fixes

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/RobotMode.java
- src/main/java/frc/robot/subsystems/led/Led.java
Picks up algae from the ground
> Algae from the ground

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/subsystems/arm/Arm.java
- src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
Fully working, and tested in sim and on the robot
> Auto Align to the Net/Barge

- src/main/java/frc/robot/subsystems/grabber/Grabber.java
Made eject not stop automatically and go until the B button is released
> Made ejection work properly

- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/config/C2025RobotFactory.java
- src/main/java/frc/robot/subsystems/drivetrain/Drivetrain.java
- src/main/java/frc/robot/subsystems/vision/Vision.java
> Merge 3rd camera code back into main.

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/Constants.java
I also fixed the auto-firing logic to work when we're not auto-aligning.
> Adjusting Coral Station Position

- src/main/java/frc/robot/CommandFactory.java
- src/main/java/frc/robot/Constants.java
- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/RobotMode.java
- src/main/java/frc/robot/SuperStructure.java
Launches the algae using the shoulder.
Moves the arm all the way backwards to 105 degrees, and then when you press fire, the arm goes vertical (90 degrees), and the grabber fires when it gets to 97 degrees.
Also moved the pose two inches closer to the net.
> Algae Net Fix
